# Generated by Django 3.2 on 2022-03-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
