# Generated by Django 3.2 on 2022-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0002_auto_20220328_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='minVersion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
