# Generated by Django 3.2 on 2022-03-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0003_auto_20220330_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='estado',
            new_name='cualificado',
        ),
    ]
