# Generated by Django 3.2 on 2022-03-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0002_auto_20220325_1707'),
        ('ietimoodle', '0004_rename_estado_entrega_cualificado'),
    ]

    operations = [
    ]
