# Generated by Django 3.2 on 2022-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0005_merge_20220330_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='archivo',
            field=models.FileField(blank=True, upload_to='./archivos/entregas/'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cualificacion',
            field=models.IntegerField(default=0),
        ),
    ]
