# Generated by Django 3.2 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0006_auto_20220404_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='vrtarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ietimoodle.vrtarea'),
        ),
        migrations.AddField(
            model_name='vrtarea',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ietimoodle.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ietimoodle.tarea'),
        ),
    ]
