# Generated by Django 3.2 on 2022-04-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0007_auto_20220404_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='ejercicio',
        ),
    ]
