# Generated by Django 3.2 on 2022-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0008_remove_tarea_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrtarea',
            name='nombre',
            field=models.CharField(default='vr laprimer', max_length=200),
            preserve_default=False,
        ),
    ]
